version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/build/

permissions:
  - object: /
    pattern: '**'
    owner: ubuntu
    group: ubuntu

hooks:
  AfterInstall:
    - location: scripts/npm-install.sh
      runas: root
      timeout: 300
  ApplicationStart:
    - location: scripts/npm-start.sh
      runas: root
      timeout: 60
  # ValidateService:
  #   - location: scripts/validate-server
  #     timeout: 30
  #     runas: root
